// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task_Reminder_Api_Project_1.Data;

#nullable disable

namespace TaskReminderApiProject1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221125134146_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Task_Reminder_Api_Project_1.Data.Models.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DayAndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsReminder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskTitle")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Reminder");
                });
#pragma warning restore 612, 618
        }
    }
}
